apiVersion: v1
kind: Service
metadata:
  name: {service-name}
  namespace: dev
  labels:
    app: {service-name}
spec:
  selector:
    app: {service-name}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8150
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {service-name}
  namespace: dev
  labels:
    app: {service-name}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {service-name}
  template:
    metadata:
      name: {service-name}
      labels:
        app: {service-name}
    spec:
      containers:
        - name: {service-name}
          image: {builded_image_url:tag}
          command: [ "./service-binary" ]
          args: []
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8150
              protocol: TCP
      restartPolicy: Always
      